// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: proto/appointment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessId    string                 `protobuf:"bytes,1,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Slots         []string               `protobuf:"bytes,3,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSlotRequest) Reset() {
	*x = CreateSlotRequest{}
	mi := &file_proto_appointment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSlotRequest) ProtoMessage() {}

func (x *CreateSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSlotRequest.ProtoReflect.Descriptor instead.
func (*CreateSlotRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSlotRequest) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *CreateSlotRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CreateSlotRequest) GetSlots() []string {
	if x != nil {
		return x.Slots
	}
	return nil
}

type SlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BusinessId    string                 `protobuf:"bytes,2,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Time          string                 `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	IsBooked      bool                   `protobuf:"varint,5,opt,name=is_booked,json=isBooked,proto3" json:"is_booked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotResponse) Reset() {
	*x = SlotResponse{}
	mi := &file_proto_appointment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotResponse) ProtoMessage() {}

func (x *SlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotResponse.ProtoReflect.Descriptor instead.
func (*SlotResponse) Descriptor() ([]byte, []int) {
	return file_proto_appointment_proto_rawDescGZIP(), []int{1}
}

func (x *SlotResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SlotResponse) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *SlotResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *SlotResponse) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *SlotResponse) GetIsBooked() bool {
	if x != nil {
		return x.IsBooked
	}
	return false
}

type SlotQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessId    string                 `protobuf:"bytes,1,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotQuery) Reset() {
	*x = SlotQuery{}
	mi := &file_proto_appointment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotQuery) ProtoMessage() {}

func (x *SlotQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotQuery.ProtoReflect.Descriptor instead.
func (*SlotQuery) Descriptor() ([]byte, []int) {
	return file_proto_appointment_proto_rawDescGZIP(), []int{2}
}

func (x *SlotQuery) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *SlotQuery) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type SlotList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*SlotResponse        `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotList) Reset() {
	*x = SlotList{}
	mi := &file_proto_appointment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotList) ProtoMessage() {}

func (x *SlotList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotList.ProtoReflect.Descriptor instead.
func (*SlotList) Descriptor() ([]byte, []int) {
	return file_proto_appointment_proto_rawDescGZIP(), []int{3}
}

func (x *SlotList) GetSlots() []*SlotResponse {
	if x != nil {
		return x.Slots
	}
	return nil
}

type AppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SlotId        string                 `protobuf:"bytes,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppointmentRequest) Reset() {
	*x = AppointmentRequest{}
	mi := &file_proto_appointment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentRequest) ProtoMessage() {}

func (x *AppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentRequest.ProtoReflect.Descriptor instead.
func (*AppointmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointment_proto_rawDescGZIP(), []int{4}
}

func (x *AppointmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AppointmentRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

type AppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SlotId        string                 `protobuf:"bytes,3,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppointmentResponse) Reset() {
	*x = AppointmentResponse{}
	mi := &file_proto_appointment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentResponse) ProtoMessage() {}

func (x *AppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentResponse.ProtoReflect.Descriptor instead.
func (*AppointmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_appointment_proto_rawDescGZIP(), []int{5}
}

func (x *AppointmentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppointmentResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AppointmentResponse) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *AppointmentResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_proto_appointment_proto protoreflect.FileDescriptor

const file_proto_appointment_proto_rawDesc = "" +
	"\n" +
	"\x17proto/appointment.proto\x12\vappointment\x1a\x1fgoogle/protobuf/timestamp.proto\"^\n" +
	"\x11CreateSlotRequest\x12\x1f\n" +
	"\vbusiness_id\x18\x01 \x01(\tR\n" +
	"businessId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x14\n" +
	"\x05slots\x18\x03 \x03(\tR\x05slots\"\x84\x01\n" +
	"\fSlotResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vbusiness_id\x18\x02 \x01(\tR\n" +
	"businessId\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x12\n" +
	"\x04time\x18\x04 \x01(\tR\x04time\x12\x1b\n" +
	"\tis_booked\x18\x05 \x01(\bR\bisBooked\"@\n" +
	"\tSlotQuery\x12\x1f\n" +
	"\vbusiness_id\x18\x01 \x01(\tR\n" +
	"businessId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\";\n" +
	"\bSlotList\x12/\n" +
	"\x05slots\x18\x01 \x03(\v2\x19.appointment.SlotResponseR\x05slots\"F\n" +
	"\x12AppointmentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\tR\x06slotId\"\x92\x01\n" +
	"\x13AppointmentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\aslot_id\x18\x03 \x01(\tR\x06slotId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xef\x01\n" +
	"\x12AppointmentService\x12G\n" +
	"\n" +
	"CreateSlot\x12\x1e.appointment.CreateSlotRequest\x1a\x19.appointment.SlotResponse\x12:\n" +
	"\tListSlots\x12\x16.appointment.SlotQuery\x1a\x15.appointment.SlotList\x12T\n" +
	"\x0fBookAppointment\x12\x1f.appointment.AppointmentRequest\x1a .appointment.AppointmentResponseB\x1bZ\x19appointment-service/protob\x06proto3"

var (
	file_proto_appointment_proto_rawDescOnce sync.Once
	file_proto_appointment_proto_rawDescData []byte
)

func file_proto_appointment_proto_rawDescGZIP() []byte {
	file_proto_appointment_proto_rawDescOnce.Do(func() {
		file_proto_appointment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_appointment_proto_rawDesc), len(file_proto_appointment_proto_rawDesc)))
	})
	return file_proto_appointment_proto_rawDescData
}

var file_proto_appointment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_appointment_proto_goTypes = []any{
	(*CreateSlotRequest)(nil),     // 0: appointment.CreateSlotRequest
	(*SlotResponse)(nil),          // 1: appointment.SlotResponse
	(*SlotQuery)(nil),             // 2: appointment.SlotQuery
	(*SlotList)(nil),              // 3: appointment.SlotList
	(*AppointmentRequest)(nil),    // 4: appointment.AppointmentRequest
	(*AppointmentResponse)(nil),   // 5: appointment.AppointmentResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_appointment_proto_depIdxs = []int32{
	1, // 0: appointment.SlotList.slots:type_name -> appointment.SlotResponse
	6, // 1: appointment.AppointmentResponse.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: appointment.AppointmentService.CreateSlot:input_type -> appointment.CreateSlotRequest
	2, // 3: appointment.AppointmentService.ListSlots:input_type -> appointment.SlotQuery
	4, // 4: appointment.AppointmentService.BookAppointment:input_type -> appointment.AppointmentRequest
	1, // 5: appointment.AppointmentService.CreateSlot:output_type -> appointment.SlotResponse
	3, // 6: appointment.AppointmentService.ListSlots:output_type -> appointment.SlotList
	5, // 7: appointment.AppointmentService.BookAppointment:output_type -> appointment.AppointmentResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_appointment_proto_init() }
func file_proto_appointment_proto_init() {
	if File_proto_appointment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_appointment_proto_rawDesc), len(file_proto_appointment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_appointment_proto_goTypes,
		DependencyIndexes: file_proto_appointment_proto_depIdxs,
		MessageInfos:      file_proto_appointment_proto_msgTypes,
	}.Build()
	File_proto_appointment_proto = out.File
	file_proto_appointment_proto_goTypes = nil
	file_proto_appointment_proto_depIdxs = nil
}
